<h1>SVC<h1>

  
 <h5>Anas Ba Ragaa _ B00075797<h5>
 <h5>Rayan Ben Daya _ B00073990 <h5>
 <h5>Rashid Alnuaimi  _ B00071921<h5>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
import pandas as pd

#new
from sklearn.svm import SVC 
from sklearn.svm import LinearSVC

# def save_array(a,filename):
#     with open(filename, 'wb') as f:
#         np.save(f, a)
# def read_array(filename):
#     with open(filename, 'rb') as f:
#         a = np.load(f)
#     return a

# X_FILE='x_file.txt'
# Y_FILE='y_file.txt'

#2 3 screenshot and explain
#4 graph nodes vs accuracy, change attributes/minimumsplit/values



In [2]:

##################################
        #Loading and Encodign #
####################################
#Machine Learning
#Assignment 2

#part 1
input_file = "Churn_Modelling.csv"
# reading file to pandas dataframe
df_ori = pd.read_csv(input_file, header = 0)
# dropping the unrelated columns
df=df_ori.drop(columns=['CustomerId', 'Surname','RowNumber'])
# Encoding the catogerical features to numerical by replacing their values with numbers
df=df.replace(["Female","Male"],[1,0])
df=df.replace(["France","Spain","Germany",],[0,1,2])
#dataset after manipulation

# Sampling to make the data balanced
df=df.sample(frac=1).groupby('Exited', sort=False).head(4000)
df
y=df['Exited'].to_numpy()
y=y.astype(int)
x=df.drop(columns=['Exited']).to_numpy()
x=x.astype(int)
x
# run only once to save file for consistency
#save_array(y,Y_FILE)
#save_array(x,X_FILE)




array([[   569,      1,      0, ...,      1,      0, 134272],
       [   705,      2,      1, ...,      1,      1, 109496],
       [   684,      1,      1, ...,      1,      0, 117038],
       ...,
       [   772,      2,      0, ...,      1,      0,  92888],
       [   708,      2,      1, ...,      0,      1, 125311],
       [   728,      0,      0, ...,      0,      0, 106977]])

In [3]:
# #Loading x and y from files
# x=read_array(X_FILE)
# y=read_array(Y_FILE)



In [9]:
#linear SVC
svc = LinearSVC()

#cross validate with k=5

cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
print(cv_results_5)

#average training score
train_score_k5=cv_results_5["train_score"]
avg_train_score_k5= sum(train_score_k5)/len(train_score_k5)
print("Average training score for LinearSVC = ", avg_train_score_k5)

#average test score
test_score_k5=cv_results_5["test_score"]
avg_test_score_k5= sum(test_score_k5)/len(test_score_k5)
print("Average testing score for LinearSVC = ", avg_test_score_k5)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


{'fit_time': array([0.41000795, 0.49926758, 0.50365162, 0.52231145, 0.54354787]), 'score_time': array([0.        , 0.00095749, 0.00099826, 0.00100112, 0.00103474]), 'test_score': array([0.65562914, 0.66142384, 0.66280033, 0.66280033, 0.66528583]), 'train_score': array([0.66224891, 0.65500104, 0.66252588, 0.66252588, 0.66335404])}
Average training score for LinearSVC =  0.6611311490661793
Average training score for LinearSVC =  0.6615878951151396


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [11]:
#SVC (Linear Kernel)
svc = SVC(kernel = 'linear')

#cross validate with k=5

cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
print(cv_results_5)

#average training score
train_score_k5=cv_results_5["train_score"]
avg_train_score_k5= sum(train_score_k5)/len(train_score_k5)
print("Average training score for SVC(Linear Kernel) = ", avg_train_score_k5)

#average test score
test_score_k5=cv_results_5["test_score"]
avg_test_score_k5= sum(test_score_k5)/len(test_score_k5)
print("Average testing score for SVC(Linear Kernel) = ", avg_test_score_k5)

{'fit_time': array([671.52015448, 650.75172949, 614.36551309, 551.30262065,
       594.0216825 ]), 'score_time': array([0.03490663, 0.03989458, 0.03291225, 0.03187227, 0.03091645]), 'test_score': array([0.67963576, 0.69619205, 0.68185584, 0.70173985, 0.68185584]), 'train_score': array([0.68419963, 0.68958376, 0.69834369, 0.69482402, 0.68385093])}
Average training score for SVC(Linear Kernel) =  0.6901604051093999
Average testing score for SVC(Linear Kernel) =  0.6882558694590607


In [12]:
#svc rbf kernal

#when gamma = auto, and c= defualt
svc = SVC(kernel = 'rbf',gamma="auto")    

cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)

test_acc =cv_results_5['test_score']
train_acc=cv_results_5['train_score']
# #average training score

print("At gamma= auto, C=default, Average training score for SVC(rbf Kernel) = ", np.mean(train_acc))

#average test score

print("At gamma= auto,C=default, Average test score for SVC(rbf Kernel) = ",np.mean(test_acc))



######## 
# tweaking gamma
########

it=[1,10,100]

print("\n\n")
for i in it:
    svc = SVC(kernel = 'rbf',gamma=i )
    
    
    print("Gamma= ",i)
    cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
    #taking train and test scores
    test_acc =cv_results_5['test_score']
    train_acc=cv_results_5['train_score']
    
    print(test_acc)
    print(train_acc)
    
    # #average training score
    print("At gamma= ",i,", Average training score for SVC(rbf Kernel) = ", np.mean(train_acc))

    #average test score
  
    print("At gamma= ",i,", Average test score for SVC(rbf Kernel) = ", np.mean(test_acc))
    print("\n\n")

    
it=[1,10,100,1000]
######## 
# tweaking C
########    
for i in it:
    svc = SVC(kernel = 'rbf',C=i,gamma="auto")
    
    
    cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
    test_acc =cv_results_5['test_score']
    train_acc=cv_results_5['train_score']

    # #average training score

    print("At C= ",i,", Average training score for SVC(rbf Kernel) = ", np.mean(train_acc))

    #average test score
    
    print("At C= ",i,", Average test score for SVC(rbf Kernel) = ", np.mean(test_acc))
    print("\n\n")

    


At gamma= auto, C=default, Average training score for SVC(rbf Kernel) =  1.0
At gamma= auto,C=default, Average test score for SVC(rbf Kernel) =  0.6625808610917552



Gamma=  1
[0.66225166 0.66225166 0.66280033 0.66280033 0.66280033]
[1. 1. 1. 1. 1.]
At gamma=  1 , Average training score for SVC(rbf Kernel) =  1.0
At gamma=  1 , Average test score for SVC(rbf Kernel) =  0.6625808610917552



Gamma=  10
[0.66225166 0.66225166 0.66280033 0.66280033 0.66280033]
[1. 1. 1. 1. 1.]
At gamma=  10 , Average training score for SVC(rbf Kernel) =  1.0
At gamma=  10 , Average test score for SVC(rbf Kernel) =  0.6625808610917552



Gamma=  100
[0.66225166 0.66225166 0.66280033 0.66280033 0.66280033]
[1. 1. 1. 1. 1.]
At gamma=  100 , Average training score for SVC(rbf Kernel) =  1.0
At gamma=  100 , Average test score for SVC(rbf Kernel) =  0.6625808610917552



At C=  1 , Average training score for SVC(rbf Kernel) =  1.0
At C=  1 , Average test score for SVC(rbf Kernel) =  0.6625808610917552



At C

In [5]:
#SVC (poly Kernel)


######## 
# tweaking degree
########

it=[2,3,5,10]

for i in it:
    svc = SVC(kernel = 'poly',degree=i, max_iter = 250000)
    
    cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
    print(cv_results_5)

    # #average training score
    train_score_k5=cv_results_5["train_score"]
    avg_train_score_k5= sum(train_score_k5)/len(train_score_k5)
    print("At degree= ",i,", Average training score for SVC(poly Kernel) = ", avg_train_score_k5)

    #average test score
    test_score_k5=cv_results_5["test_score"]
    avg_test_score_k5= sum(test_score_k5)/len(test_score_k5)
    print("At degree= ",i,", Average test score for SVC(poly Kernel) = ", avg_test_score_k5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=250000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=250000).  Consider pre

{'fit_time': array([6.50300002, 6.72917557, 6.56031489, 6.49152184, 6.69356394]), 'score_time': array([0.01196527, 0.01097059, 0.01391339, 0.01097274, 0.00997257]), 'test_score': array([0.42798013, 0.49006623, 0.45816073, 0.41507871, 0.43247722]), 'train_score': array([0.41830607, 0.47463243, 0.46521739, 0.44906832, 0.42443064])}
At degree=  2 , Average training score for SVC(poly Kernel) =  0.4463309705381608
At degree=  2 , Average test score for SVC(poly Kernel) =  0.44475260209484413


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=250000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=250000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gam

{'fit_time': array([6.50931525, 6.48140097, 6.59005952, 6.44927454, 6.48675418]), 'score_time': array([0.00598335, 0.00897598, 0.01051283, 0.0069375 , 0.01296282]), 'test_score': array([0.41556291, 0.40231788, 0.42253521, 0.6039768 , 0.45567523]), 'train_score': array([0.39821909, 0.40463864, 0.4136646 , 0.58695652, 0.44989648])}
At degree=  3 , Average training score for SVC(poly Kernel) =  0.450675066572858
At degree=  3 , Average test score for SVC(poly Kernel) =  0.4600136071591215
{'fit_time': array([0.00398898, 0.00299191, 0.00299168, 0.00299144, 0.0039897 ]), 'score_time': array([0.00099778, 0.00099754, 0.00099802, 0.00099778, 0.00099778]), 'test_score': array([0.33774834, 0.33774834, 0.33719967, 0.33719967, 0.33719967]), 'train_score': array([0.33733692, 0.33733692, 0.33747412, 0.33747412, 0.33747412])}
At degree=  5 , Average training score for SVC(poly Kernel) =  0.33741924115302346
At degree=  5 , Average test score for SVC(poly Kernel) =  0.33741913890824493
{'fit_time': ar

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=250000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale'

In [6]:
#SVC (sigmoid Kernel)


svc = SVC(kernel = 'sigmoid')
    
cv_results_5=cross_validate(svc, x, y, cv=5, return_train_score = True)
print(cv_results_5)

# #average training score
train_score_k5=cv_results_5["train_score"]
avg_train_score_k5= sum(train_score_k5)/len(train_score_k5)
print("Average training score for SVC(sigmoid Kernel) = ", avg_train_score_k5)

#average test score
test_score_k5=cv_results_5["test_score"]
avg_test_score_k5= sum(test_score_k5)/len(test_score_k5)
print("Average test score for SVC(sigmoid Kernel) = ", avg_test_score_k5)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

{'fit_time': array([0.32474613, 0.35307789, 0.36502385, 0.36506772, 0.36003661]), 'score_time': array([0.06283355, 0.07878637, 0.06382942, 0.06582332, 0.06682086]), 'test_score': array([0.66225166, 0.66225166, 0.66280033, 0.66280033, 0.66280033]), 'train_score': array([0.66266308, 0.66266308, 0.66252588, 0.66252588, 0.66252588])}
Average training score for SVC(sigmoid Kernel) =  0.6625807588469765
Average test score for SVC(sigmoid Kernel) =  0.6625808610917552
